implemented pr comments

diff --git a/preview-env/create/action.yml b/preview-env/create/action.yml
--- a/preview-env/create/action.yml
+++ b/preview-env/create/action.yml
@@ -68,41 +68,37 @@ runs:
       ref: ${{ inputs.revision }}
   - name: Deploy
     shell: bash
-    run: >-
-      if argocd app create ${{ inputs.argocd_arguments }}; then
-        echo "Creating argo cd app with name ${{ inputs.app_name }}"
-
-        # Record the start time
-        start_time=$(date +%s)
-
-        # Wait for the app to be registered
-        while true; do
-          echo "Printing app info: "
-          app_info=$(argocd app get ${{ inputs.app_name }} --output json 2>/dev/null)
-          echo "$app_info"
-
+    run: |
+      max_retries=3
+      for attempt in $(seq "$max_retries"); do
+          argocd app create ${{ inputs.argocd_arguments }}
           if [ $? -eq 0 ]; then
-            echo "App registered successfully."
-            break
+            echo "Creating Argo CD app with name ${{ inputs.app_name }}"
+            sleep 60
+
+            # Fetch app information to make sure the app is registered
+            app_info=$(argocd app get ${{ inputs.app_name }} --output json 2>/dev/null)
+            get_status_status=$?
+            if [ $get_status_status -eq 0 ] && [ -n "$app_info" ]; then
+              echo "Syncing Argo CD app..."
+
+              argocd app sync ${{ inputs.app_name }} --async --force || true
+              break
+            else
+              echo "Attempt $attempt: Failed to get app information. Retrying..."
+              continue
+            fi
           else
-            current_time=$(date +%s)
-            elapsed_time=$((current_time - start_time))
-
-            echo "Waiting for app registration... Elapsed time: $elapsed_time seconds"
-
-            # Check if 5 minutes (300 seconds) have passed
-            if [ $elapsed_time -ge 300 ]; then
-                echo "The argo cd app with name ${{ inputs.argocd_arguments }} failed to register within 5 minutes."
+            echo "Argo CD app creation failed on attempt $attempt."
+            if [ "$attempt" -eq "$max_retries" ]; then
+                echo "Max retries reached. Exiting workflow."
                 exit 1
+            else
+                echo "Attempt $attempt: Retrying in 10 seconds..."
+                sleep 10
             fi
           fi
-        done
-        echo "Syncing argo cd app..."
-        argocd app sync ${{ inputs.app_name }} --async --force || true
-      else
-        echo "argocd app creation failed. Exiting workflow."
-        exit 1
-      fi
+      done
     env:
       ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
       ARGOCD_OPTS: "--grpc-web"
@@ -111,26 +107,7 @@ runs:
     shell: bash
     run: |-
       echo "::group::wait for sync"
-      # Wait for the ArgoCD app to reach a synced and healthy state
-      # Retry if error code = PermissionDenied, as this may be a consistency problem
-      i=1
-      until \
-        error=$(argocd app wait ${{ inputs.app_name }} --timeout 1200 --health 3>&2 2>&1 1>&3);
-      do
-        error_code=$?
-        echo "$error" 1>&2
-        # Check if PermissionDenied error
-        if ! echo "$error" | grep "code = PermissionDenied" > /dev/null; then
-          exit $error_code
-        fi
-        # Exit after 5 attempts
-        if [ $i -ge 5 ]; then
-          exit $error_code
-        fi
-        echo "Retry $i ..."
-        ((i++))
-        sleep 5
-      done
+      argocd app wait ${{ inputs.app_name }} --timeout 1200 --health
       echo "::endgroup::"
     env:
       ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
