replace app health checking in a way that it won't quit prematurely

diff --git a/preview-env/create/action.yml b/preview-env/create/action.yml
--- a/preview-env/create/action.yml
+++ b/preview-env/create/action.yml
@@ -107,15 +107,34 @@ runs:
       ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
       ARGOCD_OPTS: "--grpc-web"
       ARGOCD_SERVER: ${{ inputs.argocd_server }}
-  - name: Wait for sync (up to 20 minutes)
+  - name: Wait for sync (up to 30 minutes)
     id: wait-for-sync
     shell: bash
     run: |-
       echo "::group::wait for sync"
-      argocd app wait ${{ inputs.app_name }} --timeout 1200 --health --sync
+      # argocd app wait ${{ inputs.app_name }} --timeout 1200 --health
+      # echo "::endgroup::"
+
+      TIMEOUT=1800  # Total timeout in seconds
+      INTERVAL=30   # Interval between retries in seconds
+      ELAPSED=0
+      while [ $ELAPSED -lt $TIMEOUT ]; do
+        ARGOCD_APP_STATUS=$(argocd app get "${{ inputs.app_name }}" -o json | jq -r '.status.health.status')
+        echo "Current status: $ARGOCD_APP_STATUS"
+
+        if [ "$ARGOCD_APP_STATUS" == "Healthy" ]; then
+          echo "App is healthy."
+          break
+        fi
+
+        echo "App is not healthy yet. Retrying in $INTERVAL seconds..."
+        sleep $INTERVAL
+        ELAPSED=$((ELAPSED + INTERVAL))
+      done
+
       echo "::endgroup::"
 
-      # collect application details from ArgoCD for troubleshooting
+      # collect application details for troubleshooting
       ARGOCD_APP_DETAILS=$(cat <<EOF
       App health: $(argocd app get ${{ inputs.app_name }} -o json | jq -r '.status.health.status')
       App sync: $(argocd app get ${{ inputs.app_name }} -o json | jq -r '.status.sync.status')
@@ -129,6 +148,14 @@ runs:
       echo "argocd_app_details<<EOF" >> $GITHUB_OUTPUT
       echo "$ARGOCD_APP_DETAILS" >> $GITHUB_OUTPUT
       echo "EOF" >> $GITHUB_OUTPUT
+
+      if [ "$APP_HEALTH_STATUS" == "Healthy" ]; then
+        echo "Application reached healthy state."
+        exit 0
+      else
+        echo "Timeout reached. The application did not become healthy."
+        exit 1
+      fi
 
     env:
       ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
