refactor(build-docker-image): get rid of fake credentials

diff --git a/build-docker-image/action.yml b/build-docker-image/action.yml
--- a/build-docker-image/action.yml
+++ b/build-docker-image/action.yml
@@ -9,16 +9,12 @@ inputs:
     required: true
   registry_username:
     description: Registry username used for authenticating to registry host.
-    required: true
+    required: false
   registry_password:
     description: Registry password used for authenticating to registry host.
-    required: true
-  # NOTE: Schroedinger's credentials.
-  # When using Workload Identity for authentication, technically we don't need
-  # a username and a password. But those are required inputs for the "conventional" logins.
-  # Therefore in case of using Workload Identity any username and password combination will do
-  # as they won't be used by the workflow step anyway. In this case the proper authentiaction
-  # should be handled in the caller workflow.
+    required: false
+  # When using Workload Identity for authentication, username and a password will be ignored.
+  # Providing neither will result in an error.
   use_workload_identity_auth:
     description: Use Google Workload Identity for authenticating to registry host.
     required: false
@@ -111,6 +107,12 @@ runs:
   - name: Validate inputs
     shell: bash
     run: |
+      if [ "${{ inputs.use_workload_identity_auth }}" == "false" ]; then
+        if [ -z "${{ inputs.registry_username }}" ] || [ -z "${{ inputs.registry_password }}" ]; then
+          echo "::error::When use_workload_identity_auth is false, registry_username and registry_password must be provided."
+          exit 1
+        fi
+      fi
       if [ -z "${{ inputs.registry_host }}" ]; then
         echo "Need to specify a registry host that is not empty!"
         exit 1
@@ -162,7 +164,9 @@ runs:
     # Promote switching to Google Workload Identity authentication
     shell: bash
     if: ${{ env.SHOULD_WE_PUSH == 'true' && inputs.use_workload_identity_auth == 'false' }}
-    run: echo "::warning::Workload Identity authentication is not enabled. To follow security best practices please consider switching. Proceeding with the provided credentials now."
+    run: echo "::warning::Workload Identity authentication is not enabled. To follow security best practices please consider switching. Proceeding with provided credentials."
+
+
 
   - name: Login to Docker registry
     uses: docker/login-action@v3
