Refactoring submit-test-status workflow to expect file instead of reading from stdout

diff --git a/submit-test-status/action.yml b/submit-test-status/action.yml
--- a/submit-test-status/action.yml
+++ b/submit-test-status/action.yml
@@ -6,7 +6,11 @@ description: Submits test status records from a GHA workflow job to CI Analytics
 inputs:
   test_event_record:
     description: Test event(s) in JSONL format. Required keys are test_name and test_status.
-    required: true
+    required: false
+
+  test_results_file_path:
+    description: Test results file in containing test events in JSONL format. Each line must contain at least `test_name` and `test_status` keys.
+    required: false
 
   gcp_credentials_json:
     description: Credentials for a Google Cloud ServiceAccount allowed to publish to Big Query formatted as contents of credentials.json file.
@@ -28,11 +32,48 @@ runs:
   steps:
   - name: Echo inputs
     shell: bash
+    env:
+      INPUT_FILE: "${{ (inputs.test_results_file_path != '') && inputs.test_results_file_path || (inputs.test_event_record != '') && '${{ runner.temp }}/sts/input_test_event_record.jsonl' || '' }}"
     run: |
       echo "Inputs"
       echo "-----"
       echo "Job name override: ${{ inputs.job_name_override }} (default job name: $GITHUB_JOB)"
       echo "BQ table name (for testing): ${{ inputs.big_query_table_name }}"
+      echo "Test results file path: ${{ inputs.test_results_file_path }}"
+      echo "INPUT_FILE: $INPUT_FILE"
+      echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV
+      echo "-----"
+
+  - name: Early validation - check if input is provided
+    shell: bash
+    run: |
+      if [ -z "$INPUT_FILE" ]; then
+      echo "ERROR: No input provided. Please provide either 'test_results_file_path' or 'test_event_record'."
+        exit 1
+      fi
+
+  - name: ensure that jq is available
+    uses: dcarbone/install-jq-action@v3.2.0
+
+  - name: load input
+    if: ${{ inputs.test_event_record != '' }}
+    shell: bash
+    run: |
+      mkdir -p "$(dirname "$INPUT_FILE")"
+      cat <<EOF > $INPUT_FILE
+      ${{ inputs.test_event_record }}
+      EOF
+
+  - name: validate input for file format
+    shell: bash
+    run: |
+      # validate input for the presence of mandatory keys
+      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$INPUT_FILE")
+      if [ -n "$INVALID_LINES" ]; then
+        echo "JSONL input validation failed. The following lines are invalid:"
+        echo "$INVALID_LINES"
+        exit 1
+      fi
 
   - name: login to Google Cloud
     id: auth
@@ -48,41 +89,16 @@ runs:
     run: |
       gcloud info
 
-  - name: ensure that jq is available
-    uses: dcarbone/install-jq-action@v3.2.0
-
   - name: download table schema from CI Analytics
     shell: bash
     env:
       BQ_COMMAND: "${{ (runner.os == 'Windows') && 'bq.cmd' || 'bq' }}"
     run: |
-      mkdir ${{ runner.temp }}/sts
+      mkdir -p ${{ runner.temp }}/sts
       $BQ_COMMAND show \
         --format prettyjson \
         "${{ inputs.big_query_table_name }}" \
       | jq '.schema.fields' > ${{ runner.temp }}/sts/table_schema.json
-
-  - name: load input
-    shell: bash
-    env:
-      TEMP_DIR: ${{ runner.temp }}/sts
-    run: |
-      cat <<EOF > $TEMP_DIR/input_test_event_record.json
-      ${{ inputs.test_event_record }}
-      EOF
-
-  - name: validate input
-    shell: bash
-    env:
-      TEMP_DIR: ${{ runner.temp }}/sts
-    run: |
-      # validate input for the presence of mandatory keys
-      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$TEMP_DIR/input_test_event_record.json")
-      if [ -n "$INVALID_LINES" ]; then
-        echo "JSONL input validation failed. The following lines are invalid:"
-        echo "$INVALID_LINES"
-        exit 1
-      fi
 
   - name: submit to CI Analytics
     shell: bash
@@ -98,7 +114,7 @@ runs:
         --arg BUILD_ID "$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT" \
         --arg JOB_NAME "${{ (inputs.job_name_override == '') && '$GITHUB_JOB' || inputs.job_name_override }}" \
         '. + {"report_time": $REPORT_TIME} + {"ci_url": $CI_URL} + {"build_id": $BUILD_ID} + {"job_name": $JOB_NAME}' \
-        $TEMP_DIR/input_test_event_record.json > $TEMP_DIR/test_event_record.json
+         "$INPUT_FILE" > $TEMP_DIR/enriched_test_event_records.jsonl
 
       # upload data to CI Analytics
       BQ_TABLE=$(echo "${{ inputs.big_query_table_name }}" | cut -d':' -f2)
@@ -106,5 +122,5 @@ runs:
         --source_format=NEWLINE_DELIMITED_JSON \
         --project_id=$GCP_PROJECT \
         $BQ_TABLE \
-        $TEMP_DIR/test_event_record.json \
+        $TEMP_DIR/enriched_test_event_records.jsonl \
         $TEMP_DIR/table_schema.json
