fix testing

diff --git a/.github/workflows/test-common-tooling.yml b/.github/workflows/test-common-tooling.yml
--- a/.github/workflows/test-common-tooling.yml
+++ b/.github/workflows/test-common-tooling.yml
@@ -56,6 +56,13 @@ jobs:
         else
             mvn --version
         fi
+        if ! command -v python3 &> /dev/null
+        then
+            echo "python could not be found"
+            exit 1
+        else
+            python --version
+        fi
         if ! command -v python &> /dev/null
         then
             echo "python could not be found"
